<a href="https://colab.research.google.com/github/vinods03/deep_learning/blob/main/NLP_14_Spotify_Reviews_using_Feature_Extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/spotify_reviews.csv')

In [ ]:
df.head()

Time_submitted                                             Review  \
0  2022-07-09 15:00:00  Great music service, the audio is high quality...   
1  2022-07-09 14:21:22  Please ignore previous negative rating. This a...   
2  2022-07-09 13:27:32  This pop-up "Get the best Spotify experience o...   
3  2022-07-09 13:26:45    Really buggy and terrible to use as of recently   
4  2022-07-09 13:20:49  Dear Spotify why do I get songs that I didn't ...   

   Rating  Total_thumbsup Reply  
0       5               2   NaN  
1       5               1   NaN  
2       4               0   NaN  
3       1               1   NaN  
4       1               1   NaN

In [ ]:
df = df[['Review', 'Rating', 'Total_thumbsup']]

In [ ]:
df.head()

Review  Rating  Total_thumbsup
0  Great music service, the audio is high quality...       5               2
1  Please ignore previous negative rating. This a...       5               1
2  This pop-up "Get the best Spotify experience o...       4               0
3    Really buggy and terrible to use as of recently       1               1
4  Dear Spotify why do I get songs that I didn't ...       1               1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61594 entries, 0 to 61593
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Review          61594 non-null  object
 1   Rating          61594 non-null  int64 
 2   Total_thumbsup  61594 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 1.4+ MB


In [ ]:
df.isnull().sum()

Review            0
Rating            0
Total_thumbsup    0
dtype: int64

In [ ]:
# not needed here ...

df.dropna(inplace = True)

In [ ]:
blanks = []

for i, rv, thumbsup, lb in df.itertuples():
  if rv.isspace():
    blanks = blanks.append(i)

blanks

# not needed here ...

# df.drop(blanks, inplace = True)

[]

In [ ]:
X = df['Review']
y = df['Rating']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [ ]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(49275,)
(49275,)
(12319,)
(12319,)


In [ ]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(49275,)
(49275,)
(12319,)
(12319,)


In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC

In [ ]:
pipeline = Pipeline([('tfidf', TfidfVectorizer()), ('svc', LinearSVC())])

In [ ]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('svc', LinearSVC())])

In [ ]:
y_test_pred = pipeline.predict(X_test)

In [ ]:
y_test_pred

array([5, 5, 1, ..., 5, 1, 1])

In [ ]:
import sklearn.metrics as metrics
accuracy = metrics.accuracy_score(y_test, y_test_pred)
error = 1 - accuracy
precision = metrics.precision_score(y_test, y_test_pred, average = 'weighted')
recall = metrics.recall_score(y_test, y_test_pred, average = 'weighted')
f1 = metrics.f1_score(y_test, y_test_pred, average = 'weighted')
cm = metrics.confusion_matrix(y_test, y_test_pred)

# without pos_label = 'ham', i was getting value error -> because labels were not converted to numeric ?

print('accuracy', accuracy)
print('error', error)
print('precision', precision)
print('recall', recall)
print('f1',f1)

print('\n')
print('Confusion Matrix')
print(cm)

print('\n')
from sklearn.metrics import classification_report
print(classification_report(y_test, y_test_pred))

accuracy 0.618069648510431
error 0.381930351489569
precision 0.5640210351137545
recall 0.618069648510431
f1 0.5765654379512043


Confusion Matrix
[[2921  201  120   89  204]
 [ 946  160  129   93  145]
 [ 579  141  203  246  212]
 [ 219   87  122  480  609]
 [ 222   36   60  245 3850]]


              precision    recall  f1-score   support

           1       0.60      0.83      0.69      3535
           2       0.26      0.11      0.15      1473
           3       0.32      0.15      0.20      1381
           4       0.42      0.32      0.36      1517
           5       0.77      0.87      0.82      4413

    accuracy                           0.62     12319
   macro avg       0.47      0.45      0.44     12319
weighted avg       0.56      0.62      0.58     12319



In [ ]:
# from sklearn.tree import DecisionTreeClassifier

In [ ]:
# pipeline = Pipeline([('tfidf', TfidfVectorizer()), ('dt', DecisionTreeClassifier())])

In [ ]:
# pipeline.fit(X_train, y_train)

In [ ]:
# y_test_pred = pipeline.predict(X_test)

In [ ]:
# y_test_pred

In [ ]:
# import sklearn.metrics as metrics
# accuracy = metrics.accuracy_score(y_test, y_test_pred)
# error = 1 - accuracy
# precision = metrics.precision_score(y_test, y_test_pred, average = 'weighted')
# recall = metrics.recall_score(y_test, y_test_pred, average = 'weighted')
# f1 = metrics.f1_score(y_test, y_test_pred, average = 'weighted')
# cm = metrics.confusion_matrix(y_test, y_test_pred)

# # without pos_label = 'ham', i was getting value error -> because labels were not converted to numeric ?

# print('accuracy', accuracy)
# print('error', error)
# print('precision', precision)
# print('recall', recall)
# print('f1',f1)

# print('\n')
# print('Confusion Matrix')
# print(cm)

# print('\n')
# from sklearn.metrics import classification_report
# print(classification_report(y_test, y_test_pred))

In [ ]:
# from sklearn.svm import SVC

In [ ]:
# pipeline = Pipeline([('tfidf', TfidfVectorizer()), ('svck', SVC(kernel = 'rbf'))])

In [ ]:
# pipeline.fit(X_train, y_train)

In [ ]:
# y_test_pred = pipeline.predict(X_test)

In [ ]:
# y_test_pred

In [ ]:
# import sklearn.metrics as metrics
# accuracy = metrics.accuracy_score(y_test, y_test_pred)
# error = 1 - accuracy
# precision = metrics.precision_score(y_test, y_test_pred, average = 'weighted')
# recall = metrics.recall_score(y_test, y_test_pred, average = 'weighted')
# f1 = metrics.f1_score(y_test, y_test_pred, average = 'weighted')
# cm = metrics.confusion_matrix(y_test, y_test_pred)

# # without pos_label = 'ham', i was getting value error -> because labels were not converted to numeric ?

# print('accuracy', accuracy)
# print('error', error)
# print('precision', precision)
# print('recall', recall)
# print('f1',f1)

# print('\n')
# print('Confusion Matrix')
# print(cm)

# print('\n')
# from sklearn.metrics import classification_report
# print(classification_report(y_test, y_test_pred))

In [ ]:
# Converting the Rating to Positive and Negative only to compare with NLP - 13 Spotify Reviews using Sentiment Analysis.ipynb
# The feature extraction technique gave much better results than the sentiment analysis technique

df.head()

Review  Rating  Total_thumbsup
0  Great music service, the audio is high quality...       5               2
1  Please ignore previous negative rating. This a...       5               1
2  This pop-up "Get the best Spotify experience o...       4               0
3    Really buggy and terrible to use as of recently       1               1
4  Dear Spotify why do I get songs that I didn't ...       1               1

In [ ]:
df['Rating'].replace(1, value = 'Negative', inplace = True)
df['Rating'].replace(2, value = 'Negative', inplace = True)
df['Rating'].replace(3, value = 'Negative', inplace = True)
df['Rating'].replace(4, value = 'Positive', inplace = True)
df['Rating'].replace(5, value = 'Positive', inplace = True)

In [ ]:
df.head()

Review    Rating  Total_thumbsup
0  Great music service, the audio is high quality...  Positive               2
1  Please ignore previous negative rating. This a...  Positive               1
2  This pop-up "Get the best Spotify experience o...  Positive               0
3    Really buggy and terrible to use as of recently  Negative               1
4  Dear Spotify why do I get songs that I didn't ...  Negative               1

In [ ]:
X = df['Review']
y = df['Rating']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [ ]:
pipeline = Pipeline([('tfidf', TfidfVectorizer()), ('lsvc', LinearSVC())])

In [ ]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('lsvc', LinearSVC())])

In [ ]:
y_test_pred = pipeline.predict(X_test)

In [ ]:
y_test_pred

array(['Positive', 'Positive', 'Positive', ..., 'Positive', 'Positive',
       'Negative'], dtype=object)

In [ ]:
import sklearn.metrics as metrics
accuracy = metrics.accuracy_score(y_test, y_test_pred)
error = 1 - accuracy
precision = metrics.precision_score(y_test, y_test_pred, average = 'weighted')
recall = metrics.recall_score(y_test, y_test_pred, average = 'weighted')
f1 = metrics.f1_score(y_test, y_test_pred, average = 'weighted')
cm = metrics.confusion_matrix(y_test, y_test_pred)

# without pos_label = 'ham', i was getting value error -> because labels were not converted to numeric ?

print('accuracy', accuracy)
print('error', error)
print('precision', precision)
print('recall', recall)
print('f1',f1)

print('\n')
print('Confusion Matrix')
print(cm)

print('\n')
from sklearn.metrics import classification_report
print(classification_report(y_test, y_test_pred))

accuracy 0.8682522932056174
error 0.13174770679438264
precision 0.8686396368196261
recall 0.8682522932056174
f1 0.8681658408492012


Confusion Matrix
[[5573  701]
 [ 922 5123]]


              precision    recall  f1-score   support

    Negative       0.86      0.89      0.87      6274
    Positive       0.88      0.85      0.86      6045

    accuracy                           0.87     12319
   macro avg       0.87      0.87      0.87     12319
weighted avg       0.87      0.87      0.87     12319

