<a href="https://colab.research.google.com/github/vinods03/deep_learning/blob/main/NLP_16_Music_Classification_Pop_Or_Rap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# The two genres are pop: 1 & rap: 0

In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [9]:
df = pd.read_csv('/content/drive/MyDrive/MusicDataFiles/train.csv')

In [10]:
df.head()

lyric  class
0             Can't drink without thinkin' about you      1
1              Now Lil Pump flyin' private jet (Yuh)      0
2  No, matter fact, you ain't help me when I had ...      0
3              And you could find me, I ain't hidin'      0
4          From the way you talk to the way you move      1

In [11]:
df.count()

lyric    51054
class    51054
dtype: int64

In [14]:
df.isnull().sum()

lyric    0
class    0
dtype: int64

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51054 entries, 0 to 51053
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   lyric   51054 non-null  object
 1   class   51054 non-null  int64 
dtypes: int64(1), object(1)
memory usage: 797.8+ KB


In [17]:
# not needed here actually ..
df.dropna(inplace = True)

In [18]:
df.count()

lyric    51054
class    51054
dtype: int64

In [19]:
blanks = []
for i, lyric, cls in df.itertuples():
  if lyric.isspace():
    blanks.append(i)

blanks

[]

In [20]:
# not needed here actually
df.drop(blanks, inplace = True)

In [21]:
df.count()

lyric    51054
class    51054
dtype: int64

In [22]:
X = df['lyric']
y = df['class']

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [24]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(40843,)
(10211,)
(40843,)
(10211,)


In [25]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC

In [26]:
pipeline = Pipeline([('tfidf', TfidfVectorizer()),('svc', LinearSVC())])

In [27]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('svc', LinearSVC())])

In [28]:
y_test_pred = pipeline.predict(X_test)

In [29]:
y_test_pred

array([1, 0, 0, ..., 0, 0, 0])

In [30]:
import sklearn.metrics as metrics
accuracy = metrics.accuracy_score(y_test, y_test_pred)
error = 1 - accuracy
precision = metrics.precision_score(y_test, y_test_pred, average = 'weighted')
recall = metrics.recall_score(y_test, y_test_pred, average = 'weighted')
f1 = metrics.f1_score(y_test, y_test_pred, average = 'weighted')
cm = metrics.confusion_matrix(y_test, y_test_pred)

print('accuracy', accuracy)
print('error', error)
print('precision', precision)
print('recall', recall)
print('f1',f1)

print('\n')
print('Confusion Matrix')
print(cm)

print('\n')
from sklearn.metrics import classification_report
print(classification_report(y_test, y_test_pred))

accuracy 0.8036431299578886
error 0.19635687004211144
precision 0.8047953798849913
recall 0.8036431299578886
f1 0.8040035783151588


Confusion Matrix
[[4669 1086]
 [ 919 3537]]


              precision    recall  f1-score   support

           0       0.84      0.81      0.82      5755
           1       0.77      0.79      0.78      4456

    accuracy                           0.80     10211
   macro avg       0.80      0.80      0.80     10211
weighted avg       0.80      0.80      0.80     10211



In [31]:
test_df = pd.read_csv('/content/drive/MyDrive/MusicDataFiles/test.csv')

In [32]:
test_df.head()

id                                              lyric
0   0                Now they know my name wherever I go
1   1  If your girl don't get it poppin', put me on y...
2   2              P1 cleaner than your church shoes, ah
3   3          Bodies start to drop, ayy (Hit the floor)
4   4                     I don't look to the sky no mo'

In [36]:
y_test_dataset = pipeline.predict(test_df['lyric'])

In [37]:
y_test_dataset

array([1, 0, 0, ..., 0, 0, 0])

In [39]:
y_test_0 = []

for item in y_test_dataset:
  if item == 0:
    y_test_0.append(item)

print(len(y_test_0))

1428


In [40]:
y_test_1 = []

for item in y_test_dataset:
  if item == 1:
    y_test_1.append(item)

print(len(y_test_1))

1248
