<a href="https://colab.research.google.com/github/vinods03/deep_learning/blob/main/NLP_17_Brexit_Tweets_Pro_and_Anti_using_Feature_Extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df1 = pd.read_csv('/content/drive/MyDrive/Brexit/TweetDataset_ProBrexit_Jan-Mar2022.csv')

In [ ]:
df1.head()

Unnamed: 0                 Date  Headline  \
0           0  15-Jan-2022 11:58PM       NaN   
1           1  15-Jan-2022 11:57PM       NaN   
2           2  15-Jan-2022 11:56PM       NaN   
3           3  15-Jan-2022 11:54PM       NaN   
4           4  15-Jan-2022 11:53PM       NaN   

                                                 URL  Opening Text  \
0  https://twitter.com/dianemcgregor8/statuses/14...           NaN   
1  http://twitter.com/DeniseMembery/statuses/1482...           NaN   
2  https://twitter.com/007Stirling/statuses/14825...           NaN   
3  https://twitter.com/UKleadstheworld/statuses/1...           NaN   
4  https://twitter.com/paul_beamish/statuses/1482...           NaN   

                                        Hit Sentence   Source  \
0  RT @re11ddy: QT @sandieshoes: Do this if you v...  Twitter   
1  RT @RickSacrop: Michael Fabricant is absolutel...  Twitter   
2  @StokieDrew2 I do find it rich; that Tory vote...  Twitter   
3  RT @denistmurray: Brexit Britain win as London...  Twitter   
4  @afneil If Johnson is taken down by The Tories...  Twitter   

         Influencer         Country  Subregion  ...  \
0   @dianemcgregor8        Cameroon        NaN  ...   
1    @DeniseMembery  United Kingdom        NaN  ...   
2      @007stirling  United Kingdom        NaN  ...   
3  @ukleadstheworld  United Kingdom        NaN  ...   
4     @paul_beamish  United Kingdom        NaN  ...   

             Twitter Screen Name                      User Profile Url  \
0               Diane M McGregor    https://twitter.com/dianemcgregor8   
1                      Denise M.  http://www.twitter.com/DeniseMembery   
2  Finlay Stirling 🇬🇧☘️❤️🏴󠁧󠁢󠁳󠁣󠁴󠁿       https://twitter.com/007Stirling   
3                  BestofBritish   https://twitter.com/UKleadstheworld   
4                   Paul Beamish      https://twitter.com/paul_beamish   

                                         Twitter Bio  Twitter Followers  \
0  Veggie burger! Lover of all Animals and Nature...              122.0   
1  🇬🇧✡️ Proud to be British. 🇬🇧   Animal lover, m...             5721.0   
2  BRITISH/IRISH/ULSTER-SCOTS PUL\nRIGHT-WING. \n...             7219.0   
3  GB News, Conservatives, Brexiteer, Block all ads.              700.0   
4  Brexiteer and Shipbuilder (Plater/Welder) livi...              200.0   

   Twitter Following  Alternate Date Format      Time             State  \
0              185.0           Jan 15, 2022  11:58 PM             North   
1             6291.0           Jan 15, 2022  11:57 PM           England   
2             7433.0           Jan 15, 2022  11:56 PM  Northern Ireland   
3             1014.0           Jan 15, 2022  11:54 PM               NaN   
4              822.0           Jan 15, 2022  11:53 PM           England   

      City  Document Tags  
0      NaN            NaN  
1      NaN            NaN  
2  Belfast            NaN  
3      NaN            NaN  
4      NaN            NaN  

[5 rows x 38 columns]

In [ ]:
df1 = pd.DataFrame(df1['Hit Sentence'])

In [ ]:
df1.head()

Hit Sentence
0  RT @re11ddy: QT @sandieshoes: Do this if you v...
1  RT @RickSacrop: Michael Fabricant is absolutel...
2  @StokieDrew2 I do find it rich; that Tory vote...
3  RT @denistmurray: Brexit Britain win as London...
4  @afneil If Johnson is taken down by The Tories...

In [ ]:
type(df1)

pandas.core.frame.DataFrame

In [ ]:
# 1 is pro and 0 is anti

df1['label'] = 1

In [ ]:
df1.head()

Hit Sentence  label
0  RT @re11ddy: QT @sandieshoes: Do this if you v...      1
1  RT @RickSacrop: Michael Fabricant is absolutel...      1
2  @StokieDrew2 I do find it rich; that Tory vote...      1
3  RT @denistmurray: Brexit Britain win as London...      1
4  @afneil If Johnson is taken down by The Tories...      1

In [ ]:
df1.count()

Hit Sentence    147631
label           147631
dtype: int64

In [ ]:
df2 = pd.read_csv('/content/drive/MyDrive/Brexit/TweetDataset_AntiBrexit_Jan-Mar2022.csv')

In [ ]:
df2 = pd.DataFrame(df2['Hit Sentence'])

In [ ]:
df2.head()

Hit Sentence
0  RT @cnapan: #JohnsonOut is now running at 218,...
1  RT @Femi_Sorry: My point: Any Labour leader wh...
2  RT @andy_murray: QT @Nigel_Farage: Please reco...
3  RT @mikegalsworthy: We’re the first country in...
4  RT @StevePeers: QT @andy_murray: Game, set and...

In [ ]:
df2['label'] = 0

In [ ]:
df2.head()

Hit Sentence  label
0  RT @cnapan: #JohnsonOut is now running at 218,...      0
1  RT @Femi_Sorry: My point: Any Labour leader wh...      0
2  RT @andy_murray: QT @Nigel_Farage: Please reco...      0
3  RT @mikegalsworthy: We’re the first country in...      0
4  RT @StevePeers: QT @andy_murray: Game, set and...      0

In [ ]:
df2.count()

Hit Sentence    210574
label           210574
dtype: int64

In [ ]:
df = pd.concat([df1, df2])

In [ ]:
df.count()

Hit Sentence    358205
label           358205
dtype: int64

In [ ]:
df['label'].unique()

array([1, 0])

In [ ]:
df.dropna(inplace = True)

In [ ]:
df.count()

Hit Sentence    358205
label           358205
dtype: int64

In [ ]:
blanks = []
for i, tw, lb in df.itertuples():
  if tw.isspace():
    blanks.append(i)

blanks

[]

In [ ]:
df.drop(blanks, inplace = True)

In [ ]:
df.count()

Hit Sentence    358205
label           358205
dtype: int64

In [ ]:
X = df['Hit Sentence']
y = df['label']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [ ]:
type(y_train)
y_train.unique()
y_train.value_counts()

0    168424
1    118140
Name: label, dtype: int64

In [ ]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(286564,)
(71641,)
(286564,)
(71641,)


In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC

In [ ]:
pipeline = Pipeline([('tfidf', TfidfVectorizer()),('svc',LinearSVC())])

In [ ]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('svc', LinearSVC())])

In [ ]:
y_test_pred = pipeline.predict(X_test)

In [ ]:
y_test_pred

array([0, 1, 0, ..., 0, 1, 1])

In [ ]:
import sklearn.metrics as metrics
accuracy = metrics.accuracy_score(y_test, y_test_pred)
error = 1 - accuracy
precision = metrics.precision_score(y_test, y_test_pred, average = 'weighted')
recall = metrics.recall_score(y_test, y_test_pred, average = 'weighted')
f1 = metrics.f1_score(y_test, y_test_pred, average = 'weighted')
cm = metrics.confusion_matrix(y_test, y_test_pred)

print('accuracy', accuracy)
print('error', error)
print('precision', precision)
print('recall', recall)
print('f1',f1)

print('\n')
print('Confusion Matrix')
print(cm)

print('\n')
from sklearn.metrics import classification_report
print(classification_report(y_test, y_test_pred))

accuracy 0.9132480004466716
error 0.08675199955332835
precision 0.9131337835657509
recall 0.9132480004466716
f1 0.9130128054482713


Confusion Matrix
[[39534  2616]
 [ 3599 25892]]


              precision    recall  f1-score   support

           0       0.92      0.94      0.93     42150
           1       0.91      0.88      0.89     29491

    accuracy                           0.91     71641
   macro avg       0.91      0.91      0.91     71641
weighted avg       0.91      0.91      0.91     71641



In [ ]:
validation_data = pd.DataFrame(['Brexit is so much needed for our economy !!'], columns = ['Hit Sentence'])

In [ ]:
prediction = pipeline.predict(validation_data)

In [ ]:
print(prediction) # actually this is pro-brexit but getting anti-brexit

[0]


In [ ]:
validation_data = pd.DataFrame(['Brexit might give short teerm benefits but will harm in the long run'], columns = ['Hit Sentence'])

In [ ]:
prediction = pipeline.predict(validation_data)

In [ ]:
print(prediction) # actually this is anti-brexit and getting anti-brexit

[0]
